### ISSUE TITLE
ExtraSoundsLegacy Mod Version 1.0.0 Crash by Start with Exit-Code: 1

### ISSUE THREAD

**Issue by Titoo8899** [ACGaming/ExtraSoundsLegacy#1]
Hi,
the Mod with the cool Idears crash by start and it give only this one Massage on the Screen. But it give no Crash Report what the Fail is. I hope you can check this what not work in this mod by the Start. 

Minecraft 1.12.2
Forge Version: newest Version with ending 2860

Only Pick the mod in the Mods Folder and Start Minecraft and the Minecraft will then the loading Stream is finish not Start the Launcher and Crash in the first second with this Screen mistake Exit-Code: 1

**Comment by ACGaming** [comment]
Forgot to mention it on the mod page, you need [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) to run the mod.

**Comment by Titoo8899** [comment]
ah okay Mixin

**Comment by Titoo8899** [comment]
yes work now. Thank you
