### ISSUE TITLE
Unexpected crash loading menu #2

### ISSUE THREAD

**Issue by BoraiperXD** [ACGaming/ExtraSoundsLegacy#11]
Hi It's me again, and I'm having a problem with the loading time and the black screen glitching.
Here's a report issue:
[crash-2022-11-28_20.02.33-client.txt](https://github.com/ACGaming/ExtraSoundsLegacy/files/10103513/crash-2022-11-28_20.02.33-client.txt)

Screenshots:
![image_crash_2](https://user-images.githubusercontent.com/80188692/204274193-c0efea68-7cc3-41b4-971b-f26069b9343a.png)

Ty and I hope u fix it :)

**Comment by ACGaming** [comment]
The recent versions of AssetMover are broken, you‘d have to downgrade to [version 1.1](https://www.curseforge.com/minecraft/mc-mods/assetmover/files/3822919) for the time being.
