### ISSUE TITLE
Some sounds don't work

### ISSUE THREAD

**Issue by EliteMeats** [ACGaming/ExtraSoundsLegacy#14]
Testing all of the listed sounds in the sound toggles section in the config, these were the ones that don't work even when set to true:

> Play a sound when activating, deactivating and running a beacon

> Play a sound when applying bonemeal
        
> Play a sound on player name mentions in chat

> Play a sound when planting a crop

> Play a sound when potion effects get added or removed from the player

> Play a sound when spawning an entity with a spawn egg

Tested on a clean 1.12.2 forge instance with only this mod and mixinbooter installed, on the latest version of the mod (1.4.1).

**Comment by EliteMeats** [comment]
I see, sorry about that. Is it just a matter of dropping AssetMover in to the mods folder or is there some extra configuration required to download the sounds?

**Comment by ACGaming** [comment]
It‘s just a drop-in!
