### ISSUE TITLE
Crash before game show window

### ISSUE THREAD

**Issue by AlexChevios** [ACGaming/ExtraSoundsLegacy#16]
<p>I found this mod, but after adding it to my modpack, the game crashes without even showing the loading window.</p>
<a href="https://gist.github.com/AlexChevios/673299e0ebd116b1caaa465f6bd492cc">latest.log</a>
<p>Other mods:</p>
<img src="https://user-images.githubusercontent.com/126811494/233805413-081d7afb-34b1-4670-9dec-783a4d75acbd.jpg"></img>

**Comment by ACGaming** [comment]
You have renamed your mod files. Since Forge loads mods alphabetically, the dependency `MixinBooter` loads too late in your case. That‘s why the mod file is named `!mixinbooter-7.1.jar` originally to solve this issue.
