### ISSUE TITLE
[Suggestion] New Sound Events

### ISSUE THREAD

**Issue by Lylythii** [ACGaming/ExtraSoundsLegacy#2]
Thought of some possible new sound triggering events if it interests you at all.

- Scrolling through JEI pages,
- Switching between different inventory tabs. (Creative tabs, or Modded tabs)
- Opening or closing a Book & Quill.
- Opening or closing the Recipe Book.
- Swapping items in the off-hand.
- Raising or lowering a shield.

**Comment by ACGaming** [comment]
Nice suggestions, will consider them for future updates! 👏

**Comment by ACGaming** [comment]
Implemented with 1da2296237088653e940b0d9017a1b3dccadf2b4 except shield sounds, they seem to require more work in comparison, as dull as it sounds. 😉
