### ISSUE TITLE
[Suggestion] Random Sound Suggestions

### ISSUE THREAD

**Issue by Turkey9002** [ACGaming/ExtraSoundsLegacy#6]
Just some sound event ideas. ^^;

**Backported:**
- Beacon (Activate/Ambient Loop/Deactivate/Power Selecting) ✅
- Placing/Breaking Crops ✅
- Placing/Breaking Nether Wart ✅
- Using Bone Meal ✅

**New:**
- Activating a Nether Portal (similar to when you activate the End Portal) ✅
- Crafting an item ✅
- Fireball sound when Monster Spawners activate and spawn mobs ✅
- Gaining and losing negative and positive status effects ✅
- Scrolling in the creative menu ✅

✅ = implemented in dev

**Comment by ACGaming** [comment]
Noted for future updates!
