### ISSUE TITLE
Game Menu crash

### ISSUE THREAD

**Issue by BoraiperXD** [ACGaming/ExtraSoundsLegacy#7]
When I type once on the mod options or select the world menu, it crashes my game on your latest version: ExtraSounds-1.12.2–1.3.0 except the older version of 1.2.0 is fine and safe in my modpack. Can you search and find out what happened if it's a bug or incompatibility with a mod? Thank you.
10/26/2022

Screenshots:
![2022-10-26_00 43 24_2](https://user-images.githubusercontent.com/80188692/197837232-adb2aeb6-78a8-499b-88c0-f75748e0a83b.png)
![2022-10-26_00 43 38_2](https://user-images.githubusercontent.com/80188692/197837244-3ad2be14-73c5-40a2-b839-170b510432d5.png)

Crash reports:
[crash-2022-10-26_00.43.14-client.txt](https://github.com/ACGaming/ExtraSoundsLegacy/files/9862427/crash-2022-10-26_00.43.14-client.txt)
[crash-2022-10-26_00.43.32-client.txt](https://github.com/ACGaming/ExtraSoundsLegacy/files/9862428/crash-2022-10-26_00.43.32-client.txt)

**Comment by ACGaming** [comment]
I somehow managed to reintroduce a bug I fixed rather early in the update process.
Me big dumb dumb! Hotfix coming soon.
