### ISSUE TITLE
Crash with Epic Siege mod on world join

### ISSUE THREAD

**Issue by Lylythii** [ACGaming/ExtraSoundsLegacy#9]
[latest.log](https://github.com/ACGaming/ExtraSoundsLegacy/files/10048938/latest.log)

Mods:
!mixinbooter-5.0.jar
assetmover-1.1.jar
EpicSiegeMod-13.167.jar
ExtraSounds-1.12.2-1.3.1.jar

**Comment by ACGaming** [comment]
This should already be fixed in v1.3.2. 🙂

**Comment by Lylythii** [comment]
Indeed it is, didn't notice the update!
